# Generated by Django 5.1.3 on 2024-12-19 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('link', models.URLField(verbose_name='Посилання')),
                ('login', models.CharField(max_length=255, verbose_name='Логін')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_payment_date', models.DateField(verbose_name='Дата поточного платежу')),
                ('next_payment_date', models.DateField(verbose_name='Дата наступного платежу')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума платежу')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentservice', verbose_name='Сервіс')),
            ],
        ),
    ]
