# Generated by Django 5.1.3 on 2024-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reminder_days',
            field=models.PositiveIntegerField(default=7, help_text='За скільки днів до наступного платежу сповіщати', verbose_name='Кількість днів до сповіщення'),
        ),
    ]
