# Generated by Django 5.1.3 on 2024-12-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_reminder_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reminder_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Кількість днів до сповіщення'),
        ),
    ]
