# Generated by Django 5.1.3 on 2024-12-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_reminder_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reminder_days',
            field=models.IntegerField(default=7, verbose_name='Дні до нагадування'),
        ),
    ]
