# Generated by Django 5.1.3 on 2025-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('UAH', 'Гривня'), ('EUR', 'Євро'), ('USD', 'Долар США')], default='UAH', max_length=3, verbose_name='Валюта'),
        ),
    ]
