# Generated by Django 5.1.3 on 2024-12-03 23:25

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskperformer',
            old_name='finished_at',
            new_name='completed_at',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_to_tasks', through='main.TaskPerformer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не розпочато'), ('in_progress', 'Виконується'), ('completed', 'Завершено')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_number',
            field=models.CharField(default=main.models.generate_task_number, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='taskperformer',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Виконується'), ('completed', 'Завершено')], default='in_progress', max_length=20),
        ),
    ]
