# Generated by Django 5.1.3 on 2024-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_finished_at_taskperformer_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskperformer',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не розпочато'), ('in_progress', 'Виконується'), ('completed', 'Завершено')], default='not_started', max_length=20),
        ),
    ]
