# Generated by Django 5.1.3 on 2024-12-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
