# Generated by Django 5.1.3 on 2024-12-04 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message_original_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='original_file_name',
        ),
    ]
